version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-db-compose
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodata_compose:/data/db

  app:
    build: .
    container_name: springboot-url-shortener
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/admin?authSource=admin
      SPRING_APPLICATION_NAME: url-shortener

volumes:
  mongodata_compose:
