version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-db-compose
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodata_compose:/data/db

volumes:
  mongodata_compose:
