spring:
  application:
    name: url-shortener

  docker:
    compose:
      enabled: true
      file: ./docker-compose.yml

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: url_shortener_db
      username: admin
      password: admin
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: url-shortener-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    requestreply:
      shorturlcreator:
        request: url.shortener.create.url.request
        reply: url.shortener.create.url.reply
      findurl:
        request: url.shortener.find.url.request
        reply: url.shortener.find.url.reply